name: CI
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Git tags'
        required: true
        type: string
        default: 'v5.1.17'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
        with:
          repository: rcourtman/Pulse
          ref: ${{ github.event.inputs.tag }}

      - name: Replace files
        run: |
          git clone https://github.com/${{ github.actor }}/docker-pulse /tmp/pulse
          cp -f /tmp/pulse/Dockerfile Dockerfile
          cp -f /tmp/pulse/internal/agentbinaries/host_agent.go internal/agentbinaries/host_agent.go
          

      - name: Extract tags
        id: vars
        run: |
          VERSION=${{ github.event.inputs.tag }}
          VERSION=${VERSION#v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.actor }}/pulse
          tags: |
            latest
            ${{ steps.vars.outputs.VERSION }}

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          provenance: false
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
